### ISSUE TITLE
Automatically generate grades on some event

### ISSUE THREAD

**Issue by red-tt-bear** [rederlyhq/backend#41]
This is an extension of #27
In the resolution we simply made a cli that made sure all student enrollments had a grade, even if 0
In the future we will need to determine at what time grades are created and how to handle changes to the course

Changes to the course include:
removal of a question, topic, unit, or the course itself

Events could be:
On enrollment
On topic start
On course start
On course edit

We need a student grade for every question for data consistency on the analytics side and shorter queries on the application side

**Comment by tommylettieri** [comment]
Can't be start date because of lazy (or professors that are out of time), maybe there should be an explicit answer

Activation of topic call

assign/unassign

flag on a topic on a course

**Comment by red-tt-bear** [comment]
@doombot-exe and I discussed that this event should be:
Topic creation
Student enrollment

**Comment by doombot-exe** [comment]
with an eye towards an explicit instructor action to "assign" a topic -- replacing topic creation as a trigger. Student enrollment would still need to remain a trigger.

**Comment by red-tt-bear** [comment]
Query for finding missing grades for user (for use with new enrollment)
```SQL
SELECT question.course_topic_question_id FROM
course_unit_content unit
INNER JOIN course_topic_content topic ON topic.course_unit_content_id = unit.course_unit_content_id
INNER JOIN course_topic_question question ON question.course_topic_content_id = topic.course_topic_content_id
LEFT JOIN student_grade grade ON grade.course_topic_question_id = topic.course_topic_content_id AND grade.user_id = 1
WHERE grade.student_grade_id IS NULL
```

**Comment by red-tt-bear** [comment]
Query for populating questions when questions are created
```SQL
SELECT e.user_id
FROM course_topic_question q
INNER JOIN course_topic_content t ON q.course_topic_content_id = t.course_topic_content_id
INNER JOIN course_unit_content u ON t.course_unit_content_id = u.course_unit_content_id
INNER JOIN student_enrollment e ON e.course_id = u.course_id
LEFT JOIN student_grade g ON g.course_topic_question_id = q.course_topic_question_id -- Avoid trying to create a grade if it already exists
WHERE q.course_topic_question_id = 4 -- This id would come from the question you want to add the grades for
AND g.student_grade_id IS NULL
```
